### ISSUE TITLE
校园卡-提交晨检信息接口

### ISSUE THREAD

**Issue by loveyouender** [ggg17226/hcQuestion#2]
晨检信息提交接口：
地址：/healthCard/addPneumonia
入参：{"skmId":"3608d028ac220f72ff0254f694fb8189","todayTemperature":true,"temperature":"37.5","whereNow":0,"havaSymptom":"2$5$8","isUnderWatch":1,"isSeek":2,"isContactTravelPeople":2,"isTravel":true,"liveHaveSymptom":true,"isInSchool":false,"isReturnSchool":false,"remark":"测试"}
返回：{"success":false,"code":11111,"message":"提交失败","data":null}

**Comment by ggg17226** [comment]
@杨良(aghost)

**Comment by ggg17226** [comment]
{
    "success": false,
    "code": 11111,
    "message": "未查找到该用户信息",
    "data": null
}
等待后续造数据

**Comment by loveyouender** [comment]
{"success":false,"code":11111,"message":"未查找到该用户信息","data":null}

**Comment by loveyouender** [comment]
是否可以提供一个有效的skmId？便于测试

**Comment by ggg17226** [comment]
@陈煜（卿愿）

**Comment by ggg17226** [comment]
35e41f50671f8eba0189791dce071515

**Comment by loveyouender** [comment]
可以了，谢谢
入参：{"skmId":"35e41f50671f8eba0189791dce071515","todayTemperature":true,"temperature":"37.6","whereNow":0,"havaSymptom":"1$3$5$6","isUnderWatch":1,"isSeek":2,"isContactTravelPeople":2,"isTravel":false,"liveHaveSymptom":false,"isInSchool":true,"isReturnSchool":true,"remark":"测试"}
返回：{"success":true,"code":10000,"message":"提交成功","data":null}
