### ISSUE TITLE
健康卡列表返回数据不对

### ISSUE THREAD

**Issue by luyanhua** [ggg17226/hcQuestion#3]
schoolName  改为school
skmId 返回 一个正确的的id  例如：35e41f50671f8eba0189791dce071515

**Comment by chenyu1128** [comment]
schoolName 改为school 能否直接用schoolName

**Comment by ggg17226** [comment]
@chenyu1128 (陈昱)

**Comment by luyanhua** [comment]
https://sk-cs.tgovcloud.com/healthCard/healthCard/getHealthCardList

**Comment by chenyu1128** [comment]
已经返回指定skmid@luyanhua

**Comment by lishaobobo** [comment]
需要在加一条测试数据 type换个类型

**Comment by chenyu1128** [comment]
@lishaobobo

**Comment by chenyu1128** [comment]
已经追加
